#!/bin/python

# DO NOT COMMIT WITH YOUR ACTUAL SECRETS EVER!!!

API_KEY ='KEY'
API_SECRET = 'SECRET'
RETURN_URL = 'http://localhost:8000'
USER_TOKEN = 'USER'
USER_SECRET = 'SECRET'
LINKEDIN_USERNAME = 'EMAIL'
LINKEDIN_PASSWORD = 'PASSWORD'


